project: 
  type: website
  
website: 
  page-navigation: true
  title: "Python snippet" 
  site-url: "https://nguyenngocbinh.github.io/python_snippet" 
  repo-url: https://github.com/nguyenngocbinh/python_snippet
  repo-actions: [edit, issue]
  
  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; CC-By NguyenNgocBinh, 2023"
    
  sidebar:
    logo: "images/openscapes_hex.png"
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://nguyenngocbinh.github.io/python_snippet
        text: "nguyenngocbinh.github.io/python_snippet"
      - icon: github
        href: https://github.com/nguyenngocbinh/python_snippet
        text: "Quarto website tutorial"
      - icon: twitter
        href: https://twitter.com/nanabi88
        text: "nanabi88 Twitter"         

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Welcome
      - explore.qmd
      - readme.md
      - tradding/trade_snippets.md
      - section: quarto-workflows/index.qmd
        contents: 
          - quarto-workflows/browser.md
          - quarto-workflows/rstudio.qmd
          - quarto-workflows/jupyter.md 
      - learning-more.qmd
      - href: transition-from-rmarkdown.qmd
        text: Transition from Rmd


format:
  html:
    theme:
      light: [cosmo, theme.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto

  
